import { engine, type EasterEgg } from "./engine"

const eggs: EasterEgg[] = [
  { id: "egg-1", name: "Codigo Konami", category: "keyboard", hint: "Arriba, arriba, abajo, abajo..." },
  { id: "egg-2", name: "Saludo Digital", category: "keyboard", hint: "Escribe un saludo clasico" },
  { id: "egg-3", name: "Pildora Roja", category: "keyboard", hint: "Entra en la matrix con tu teclado" },
  { id: "egg-4", name: "Fiesta Secreta", category: "keyboard", hint: "La fiesta empieza cuando la escribes" },
  { id: "egg-5", name: "Espejo Invertido", category: "keyboard", hint: "Todo al reves, letra por letra" },
  { id: "egg-6", name: "Onda Teal", category: "keyboard", hint: "El color favorito tiene nombre" },
  { id: "egg-7", name: "Dedos Veloces", category: "keyboard", hint: "Escribe rapido, muy rapido" },
  { id: "egg-8", name: "Modo Calma", category: "keyboard", hint: "Busca la paz interior tecleando" },
  { id: "egg-9", name: "Recarga Cafeina", category: "keyboard", hint: "La bebida del programador" },
  { id: "egg-10", name: "Permisos de Root", category: "keyboard", hint: "Necesitas privilegios elevados" },

  { id: "egg-11", name: "Persistencia Premiada", category: "click", hint: "El logo esconde algo si insistes 7 veces" },
  { id: "egg-12", name: "Triple Identidad", category: "click", hint: "El nombre revela mas con tres toques rapidos" },
  { id: "egg-13", name: "Retrato Interactivo", category: "click", hint: "La foto responde a tu insistencia" },
  { id: "egg-14", name: "Presion Sostenida", category: "click", hint: "Mantene presionada una tarjeta y espera" },
  { id: "egg-15", name: "Doble Impacto", category: "click", hint: "Los titulos reaccionan al doble clic" },
  { id: "egg-16", name: "Punto Camaleon", category: "click", hint: "Un punto pequeño cambia de color al tocarlo" },
  { id: "egg-17", name: "Rafaga al Pie", category: "click", hint: "Clics rapidos en el pie de pagina" },
  { id: "egg-18", name: "Vacio Creativo", category: "click", hint: "Cliquea 20 veces donde no hay nada" },
  { id: "egg-19", name: "Clic Modificado", category: "click", hint: "Shift cambia el significado de un clic en la navegacion" },
  { id: "egg-20", name: "Pulso Luminoso", category: "click", hint: "El punto del logo tiene ritmo propio" },
  { id: "egg-21", name: "Menu Alternativo", category: "click", hint: "El clic derecho no siempre es igual" },
  { id: "egg-22", name: "Insignia Activa", category: "click", hint: "La insignia de disponibilidad reacciona al tacto" },
  { id: "egg-23", name: "Contador Oculto", category: "click", hint: "El puntaje de velocidad esconde un contador" },
  { id: "egg-24", name: "Boton Misterioso", category: "click", hint: "El boton de mas tiene niveles secretos" },
  { id: "egg-25", name: "Perspectiva 3D", category: "click", hint: "Las tarjetas siguen tu cursor con profundidad" },

  { id: "egg-36", name: "Visitante Nocturno", category: "time", hint: "La medianoche trae secretos" },
  { id: "egg-37", name: "Sol del Mediodia", category: "time", hint: "Las 12 en punto del dia" },
  { id: "egg-38", name: "Descanso Merecido", category: "time", hint: "Los fines de semana son diferentes" },
  { id: "egg-39", name: "Cinco Minutos", category: "time", hint: "Quedate un rato, cinco minutos al menos" },
  { id: "egg-40", name: "Primera Vez", category: "time", hint: "La primera visita siempre es especial" },
  { id: "egg-41", name: "Bienvenido de Vuelta", category: "time", hint: "Volver tiene su recompensa" },
  { id: "egg-42", name: "Ano Nuevo Digital", category: "time", hint: "Empieza el ano con estilo" },
  { id: "egg-43", name: "Noche Buena Web", category: "time", hint: "Navidad trae sorpresas a la pagina" },
  { id: "egg-44", name: "Octubre Tenebroso", category: "time", hint: "El decimo mes tine un tinte especial" },
  { id: "egg-45", name: "Maraton Digital", category: "time", hint: "Diez minutos sin cerrar la pestaña" },

  { id: "egg-46", name: "Mirada Fija", category: "hover", hint: "Mira el avatar fijamente por 5 segundos" },
  { id: "egg-47", name: "Circulos de Raton", category: "hover", hint: "Dibuja circulos con el mouse" },
  { id: "egg-48", name: "Esquina Curiosa", category: "hover", hint: "Algo se asoma desde las esquinas" },
  { id: "egg-49", name: "Salvapantallas", category: "hover", hint: "Deja el mouse quieto mucho tiempo" },
  { id: "egg-50", name: "Dato Curioso", category: "hover", hint: "Las habilidades esconden datos al pasar el cursor" },
  { id: "egg-51", name: "Susurro Verde", category: "hover", hint: "El icono de WhatsApp tiene algo que decir" },
  { id: "egg-53", name: "Resplandor Teal", category: "hover", hint: "El hover prolongado ilumina de teal" },
  { id: "egg-54", name: "Atraccion Magnetica", category: "hover", hint: "Algunos elementos siguen tu cursor" },
  { id: "egg-55", name: "Viajero del Tiempo", category: "hover", hint: "Los años de experiencia esconden historias" },

  { id: "egg-56", name: "Pagina Secreta", category: "hidden", hint: "Existe una URL que no esta en el menu" },
  { id: "egg-57", name: "Creditos Finales", category: "hidden", hint: "Como en las peliculas, hay creditos ocultos" },
  { id: "egg-58", name: "Modo Depuracion", category: "hidden", hint: "Los desarrolladores tienen herramientas secretas" },
  { id: "egg-59", name: "Viaje al Pasado", category: "hidden", hint: "Un tema retro espera ser activado" },
  { id: "egg-60", name: "Lado Luminoso", category: "hidden", hint: "La luz tambien tiene su version" },
  { id: "egg-61", name: "Fiesta Cromatica", category: "hidden", hint: "Un tema que celebra con colores" },
  { id: "egg-62", name: "Serpiente 404", category: "hidden", hint: "Perderse tiene su juego" },
  { id: "egg-63", name: "Galleta de la Suerte", category: "hidden", hint: "Una API esconde mensajes sabios" },
  { id: "egg-64", name: "En las Sombras", category: "hidden", hint: "Navegando donde nadie te ve... o eso crees" },
  { id: "egg-65", name: "Curiosito", category: "hidden", hint: "El inspector de elementos revela mas de lo que crees" },

  { id: "egg-66", name: "Validacion Animada", category: "form", hint: "Un email valido desata una animacion" },
  { id: "egg-67", name: "Formulario Vacio", category: "form", hint: "Enviar sin escribir tiene consecuencias divertidas" },
  { id: "egg-68", name: "Nombre de Prueba", category: "form", hint: "Los testers siempre usan el mismo nombre" },
  { id: "egg-69", name: "Autodeteccion", category: "form", hint: "Escribi el nombre del dueno del sitio" },
  { id: "egg-70", name: "Lluvia de Exito", category: "form", hint: "Un envio exitoso merece celebracion" },
  { id: "egg-71", name: "Busqueda Secreta", category: "form", hint: "Busca la palabra easter egg" },
  { id: "egg-72", name: "Busca y Juega", category: "form", hint: "Buscar juego activa algo inesperado" },
  { id: "egg-73", name: "Busca Estilo", category: "form", hint: "Buscar tema cambia la apariencia" },
  { id: "egg-74", name: "Busca Melodia", category: "form", hint: "Buscar musica tiene ritmo" },
  { id: "egg-75", name: "Busca Sonrisa", category: "form", hint: "Buscar algo alegre tiene efecto" },

  { id: "egg-76", name: "Serpiente Clasica", category: "game", hint: "El juego mas clasico de los telefonos" },
  { id: "egg-77", name: "Carrera de Teclas", category: "game", hint: "Tipea lo mas rapido que puedas" },
  { id: "egg-78", name: "Memoria Visual", category: "game", hint: "Encuentra los pares escondidos" },
  { id: "egg-79", name: "Desafio de Clics", category: "game", hint: "Cuantos clics en 10 segundos?" },
  { id: "egg-80", name: "Caza Bichos", category: "game", hint: "Los bugs aparecen, atrapalos" },
  { id: "egg-81", name: "Pixel por Pixel", category: "game", hint: "Crea arte con cuadrados diminutos" },
  { id: "egg-82", name: "Quiz Web", category: "game", hint: "Cuanto sabes de desarrollo web?" },
  { id: "egg-83", name: "Adivina el Score", category: "game", hint: "Podes adivinar el PageSpeed?" },
  { id: "egg-84", name: "Rompe Bloques", category: "game", hint: "El clasico juego de ladrillos" },
  { id: "egg-85", name: "Trivia CSS", category: "game", hint: "Pon a prueba tus conocimientos de estilos" },

  { id: "egg-86", name: "Primer Paso", category: "achievement", hint: "Tu primera visita ya es un logro" },
  { id: "egg-87", name: "Explorador Nato", category: "achievement", hint: "Visita todas las secciones de la pagina" },
  { id: "egg-88", name: "Buho Nocturno", category: "achievement", hint: "Navega cuando todos duermen" },
  { id: "egg-89", name: "Lector Veloz", category: "achievement", hint: "Recorre todo el contenido en menos de un minuto" },
  { id: "egg-90", name: "Gato Curioso", category: "achievement", hint: "Haz clic en 20 elementos diferentes" },
  { id: "egg-91", name: "Maestro Konami", category: "achievement", hint: "Domina el codigo legendario" },
  { id: "egg-92", name: "Mariposa Social", category: "achievement", hint: "Visita todos los enlaces sociales" },
  { id: "egg-93", name: "Cazador de Huevos x10", category: "achievement", hint: "Descubri 10 easter eggs" },
  { id: "egg-94", name: "Coleccionista x50", category: "achievement", hint: "La mitad del camino esta completa" },
  { id: "egg-95", name: "Leyenda x100", category: "achievement", hint: "Solo los mas dedicados llegan a 100" },

  { id: "egg-96", name: "Fondo en Movimiento", category: "visual", hint: "El fondo tiene capas que se mueven contigo" },
  { id: "egg-97", name: "Cursor Transformado", category: "visual", hint: "Tu cursor no siempre es una flecha" },
  { id: "egg-98", name: "Textura al Tacto", category: "visual", hint: "El hover revela granulado en las superficies" },
  { id: "egg-99", name: "Particulas Teal", category: "visual", hint: "Particulas flotantes del color insignia" },
  { id: "egg-100", name: "Sonidos de Clic", category: "visual", hint: "Activa el sonido y hace clic" },
  { id: "egg-101", name: "Estela Arcoiris", category: "visual", hint: "Tu cursor deja un rastro colorido" },
  { id: "egg-102", name: "Titulo Cambiante", category: "visual", hint: "Cambia de pestaña y mira el titulo" },
  { id: "egg-103", name: "Favicon Secreto", category: "visual", hint: "El icono de la pestaña no es permanente" },
]

engine.registerMany(eggs)
